services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  firebase:
    build: ./firebase-docker
    working_dir: /workspace
    entrypoint: ['firebase', 'emulators:start', '--only', 'firestore,database']
    ports:
      - '4000-4040:4000-4040'
    volumes:
      - ./firebase:/workspace

volumes:
  mysql_data:
  mongo_data:
